# Generated by Django 2.2.6 on 2020-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blog_relation_+', to='blog.Blog', verbose_name='関連'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='タグ'),
        ),
    ]
